services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: wixiweb_laravel_tests
        working_dir: /app
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            mysql:
                condition: service_healthy
            mailpit:
                condition: service_healthy
        networks:
            - wixiweb-laravel
    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'tests'
            MYSQL_USER: 'wixiweb-laravel'
            MYSQL_PASSWORD: 'password'
        ports:
            - "8001:3306"
        restart: always
        networks:
            - wixiweb-laravel
        volumes:
            - ./mysql-init:/docker-entrypoint-initdb.d
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '8126:1025'
            - '8125:8025'
        networks:
            - wixiweb-laravel
networks:
    wixiweb-laravel:
        driver: bridge
